-- =====================================================================
-- Smart HAS / Digital 360 - Fase 6
-- Script 02: Carga de dados simulados (usuarios, cursos, pedidos,
--            sensores IoT e leituras)
-- ---------------------------------------------------------------------
-- Todos os nomes e CPFs sao FICTICIOS (dados simulados para avaliacao).
-- Os pedidos 1 a 4 espelham o mock do app Flutter (mock_data.dart),
-- para que o app e o banco mostrem os mesmos dados na demonstracao.
-- =====================================================================

-- ---------------- Usuarios ----------------
INSERT INTO T_SH_USUARIO (ID_USUARIO, NM_USUARIO, NM_LOGIN, NR_CPF, DT_NASCIMENTO, DS_PERFIL, NM_REGIAO, DT_CADASTRO)
VALUES (1, 'Maria Aparecida Lima', 'maria.lima', '10000000001', DATE '1952-03-14', 'IDOSO', 'Sao Paulo - Zona Leste', DATE '2026-02-10');
INSERT INTO T_SH_USUARIO (ID_USUARIO, NM_USUARIO, NM_LOGIN, NR_CPF, DT_NASCIMENTO, DS_PERFIL, NM_REGIAO, DT_CADASTRO)
VALUES (2, 'Jose Carlos Pereira', 'jose.pereira', '10000000002', DATE '1948-11-02', 'IDOSO', 'Sao Paulo - Centro', DATE '2026-02-18');
INSERT INTO T_SH_USUARIO (ID_USUARIO, NM_USUARIO, NM_LOGIN, NR_CPF, DT_NASCIMENTO, DS_PERFIL, NM_REGIAO, DT_CADASTRO)
VALUES (3, 'Ana Beatriz Souza', 'ana.souza', '10000000003', DATE '1975-07-21', 'ADULTO', 'Sao Paulo - Zona Sul', DATE '2026-03-05');
INSERT INTO T_SH_USUARIO (ID_USUARIO, NM_USUARIO, NM_LOGIN, NR_CPF, DT_NASCIMENTO, DS_PERFIL, NM_REGIAO, DT_CADASTRO)
VALUES (4, 'Antonio Ferreira', 'antonio.f', '10000000004', DATE '1958-01-30', 'IDOSO', 'Sao Paulo - Zona Norte', DATE '2026-03-22');
INSERT INTO T_SH_USUARIO (ID_USUARIO, NM_USUARIO, NM_LOGIN, NR_CPF, DT_NASCIMENTO, DS_PERFIL, NM_REGIAO, DT_CADASTRO)
VALUES (5, 'Lucia Helena Costa', 'lucia.costa', '10000000005', DATE '1966-09-09', 'ADULTO', 'Sao Paulo - Zona Leste', DATE '2026-04-11');
INSERT INTO T_SH_USUARIO (ID_USUARIO, NM_USUARIO, NM_LOGIN, NR_CPF, DT_NASCIMENTO, DS_PERFIL, NM_REGIAO, DT_CADASTRO)
VALUES (6, 'Pedro Henrique Alves', 'pedro.tutor', '10000000006', DATE '2002-05-17', 'TUTOR', 'Sao Paulo - Centro', DATE '2026-04-30');

-- ---------------- Cursos (trilhas) ----------------
INSERT INTO T_SH_CURSO (ID_CURSO, DS_TITULO, DS_NIVEL, NR_CARGA_HORARIA, NR_TOTAL_MODULOS)
VALUES (1, 'Primeiros passos no celular', 'BASICO', 4, 6);
INSERT INTO T_SH_CURSO (ID_CURSO, DS_TITULO, DS_NIVEL, NR_CARGA_HORARIA, NR_TOTAL_MODULOS)
VALUES (2, 'Usando o gov.br', 'INTERMEDIARIO', 6, 8);
INSERT INTO T_SH_CURSO (ID_CURSO, DS_TITULO, DS_NIVEL, NR_CARGA_HORARIA, NR_TOTAL_MODULOS)
VALUES (3, 'Seguranca digital e golpes', 'INTERMEDIARIO', 5, 7);
INSERT INTO T_SH_CURSO (ID_CURSO, DS_TITULO, DS_NIVEL, NR_CARGA_HORARIA, NR_TOTAL_MODULOS)
VALUES (4, 'Pix e pagamentos digitais', 'AVANCADO', 8, 10);

-- ---------------- Matriculas (progresso) ----------------
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (1, 1, 1, 75,  DATE '2026-02-11');
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (2, 1, 2, 30,  DATE '2026-03-01');
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (3, 1, 3, 0,   DATE '2026-05-20');
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (4, 2, 1, 100, DATE '2026-02-19');
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (5, 2, 4, 10,  DATE '2026-04-02');
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (6, 3, 2, 90,  DATE '2026-03-06');
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (7, 3, 4, 60,  DATE '2026-04-15');
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (8, 4, 1, 20,  DATE '2026-03-23');
INSERT INTO T_SH_MATRICULA (ID_MATRICULA, ID_USUARIO, ID_CURSO, NR_PROGRESSO, DT_INICIO) VALUES (9, 5, 3, 45,  DATE '2026-04-12');

-- ---------------- Servicos publicos ----------------
INSERT INTO T_SH_SERVICO (ID_SERVICO, DS_TITULO, DS_CATEGORIA, NM_ORGAO) VALUES (1, 'Consultar beneficio do INSS', 'Previdencia', 'INSS');
INSERT INTO T_SH_SERVICO (ID_SERVICO, DS_TITULO, DS_CATEGORIA, NM_ORGAO) VALUES (2, 'Agendar consulta no SUS', 'Saude', 'SUS');
INSERT INTO T_SH_SERVICO (ID_SERVICO, DS_TITULO, DS_CATEGORIA, NM_ORGAO) VALUES (3, 'Emitir 2a via do RG/CPF', 'Documentos', 'gov.br');
INSERT INTO T_SH_SERVICO (ID_SERVICO, DS_TITULO, DS_CATEGORIA, NM_ORGAO) VALUES (4, 'Consultar Bolsa Familia', 'Assistencia Social', 'Caixa');

-- ---------------- Favoritos ----------------
INSERT INTO T_SH_FAVORITO (ID_USUARIO, ID_SERVICO, DT_FAVORITO) VALUES (1, 1, DATE '2026-02-12');
INSERT INTO T_SH_FAVORITO (ID_USUARIO, ID_SERVICO, DT_FAVORITO) VALUES (1, 2, DATE '2026-03-03');
INSERT INTO T_SH_FAVORITO (ID_USUARIO, ID_SERVICO, DT_FAVORITO) VALUES (2, 1, DATE '2026-02-20');
INSERT INTO T_SH_FAVORITO (ID_USUARIO, ID_SERVICO, DT_FAVORITO) VALUES (4, 2, DATE '2026-03-25');
INSERT INTO T_SH_FAVORITO (ID_USUARIO, ID_SERVICO, DT_FAVORITO) VALUES (5, 4, DATE '2026-04-13');

-- ---------------- Pedidos (AI Logistics / Leroy Merlin) ----------------
INSERT INTO T_SH_PEDIDO (ID_PEDIDO, CD_PEDIDO, ID_USUARIO, DS_PRODUTO, DS_TIPO_PRODUTO, DS_REGIAO_ENTREGA, NR_DISTANCIA_KM,
                         DT_PRAZO, ST_PEDIDO, NM_PARCEIRO, FL_ESTOQUE, NR_HIST_ATRASOS, NR_REAGENDAMENTOS, VL_LATITUDE, VL_LONGITUDE)
VALUES (1, 'LM-2026-0001', 2, 'Kit ferramentas basicas', 'Ferramentas', 'Sao Paulo - Centro', 8,
        DATE '2026-06-16', 'EM_TRANSITO', 'Loggi', 'S', 0, 0, -23.550500, -46.633300);
INSERT INTO T_SH_PEDIDO (ID_PEDIDO, CD_PEDIDO, ID_USUARIO, DS_PRODUTO, DS_TIPO_PRODUTO, DS_REGIAO_ENTREGA, NR_DISTANCIA_KM,
                         DT_PRAZO, ST_PEDIDO, NM_PARCEIRO, FL_ESTOQUE, NR_HIST_ATRASOS, NR_REAGENDAMENTOS, VL_LATITUDE, VL_LONGITUDE)
VALUES (2, 'LM-2026-0002', 1, 'Tinta acrilica 18L', 'Pintura', 'Sao Paulo - Zona Leste', 22,
        DATE '2026-06-15', 'ATRASADO', 'Total Express', 'N', 3, 2, -23.540000, -46.490000);
INSERT INTO T_SH_PEDIDO (ID_PEDIDO, CD_PEDIDO, ID_USUARIO, DS_PRODUTO, DS_TIPO_PRODUTO, DS_REGIAO_ENTREGA, NR_DISTANCIA_KM,
                         DT_PRAZO, ST_PEDIDO, NM_PARCEIRO, FL_ESTOQUE, NR_HIST_ATRASOS, NR_REAGENDAMENTOS, VL_LATITUDE, VL_LONGITUDE)
VALUES (3, 'LM-2026-0003', 3, 'Furadeira de impacto', 'Ferramentas eletricas', 'Sao Paulo - Zona Sul', 14,
        DATE '2026-06-18', 'PENDENTE', 'Correios', 'S', 1, 0, -23.650000, -46.700000);
INSERT INTO T_SH_PEDIDO (ID_PEDIDO, CD_PEDIDO, ID_USUARIO, DS_PRODUTO, DS_TIPO_PRODUTO, DS_REGIAO_ENTREGA, NR_DISTANCIA_KM,
                         DT_PRAZO, ST_PEDIDO, NM_PARCEIRO, FL_ESTOQUE, NR_HIST_ATRASOS, NR_REAGENDAMENTOS, VL_LATITUDE, VL_LONGITUDE)
VALUES (4, 'LM-2026-0004', 4, 'Piso laminado (10 caixas)', 'Revestimento', 'Sao Paulo - Zona Norte', 19,
        DATE '2026-06-14', 'ENTREGUE', 'Loggi', 'S', 0, 0, -23.480000, -46.620000);
INSERT INTO T_SH_PEDIDO (ID_PEDIDO, CD_PEDIDO, ID_USUARIO, DS_PRODUTO, DS_TIPO_PRODUTO, DS_REGIAO_ENTREGA, NR_DISTANCIA_KM,
                         DT_PRAZO, ST_PEDIDO, NM_PARCEIRO, FL_ESTOQUE, NR_HIST_ATRASOS, NR_REAGENDAMENTOS, VL_LATITUDE, VL_LONGITUDE)
VALUES (5, 'LM-2026-0005', 5, 'Ventilador de teto', 'Eletrico', 'Sao Paulo - Zona Leste', 25,
        DATE '2026-06-20', 'EM_TRANSITO', 'Correios', 'S', 1, 1, -23.545000, -46.475000);

-- ---------------- Sensores IoT ----------------
INSERT INTO T_SH_SENSOR (ID_SENSOR, ID_PEDIDO, DS_TIPO, DS_UNIDADE, VL_LIMITE_MIN, VL_LIMITE_MAX, DS_LOCALIZACAO)
VALUES (1, 2, 'TEMPERATURA', 'C', 5, 40, 'Bau do veiculo - tinta');
INSERT INTO T_SH_SENSOR (ID_SENSOR, ID_PEDIDO, DS_TIPO, DS_UNIDADE, VL_LIMITE_MIN, VL_LIMITE_MAX, DS_LOCALIZACAO)
VALUES (2, 4, 'UMIDADE', '%', 30, 65, 'Palete do piso laminado');
INSERT INTO T_SH_SENSOR (ID_SENSOR, ID_PEDIDO, DS_TIPO, DS_UNIDADE, VL_LIMITE_MIN, VL_LIMITE_MAX, DS_LOCALIZACAO)
VALUES (3, 3, 'VIBRACAO', 'g', 0, 3, 'Caixa da furadeira');
INSERT INTO T_SH_SENSOR (ID_SENSOR, ID_PEDIDO, DS_TIPO, DS_UNIDADE, VL_LIMITE_MIN, VL_LIMITE_MAX, DS_LOCALIZACAO)
VALUES (4, 1, 'UMIDADE', '%', 20, 70, 'Caixa do kit de ferramentas');
INSERT INTO T_SH_SENSOR (ID_SENSOR, ID_PEDIDO, DS_TIPO, DS_UNIDADE, VL_LIMITE_MIN, VL_LIMITE_MAX, DS_LOCALIZACAO)
VALUES (5, 5, 'VIBRACAO', 'g', 0, 2.5, 'Caixa do ventilador');

-- ---------------- Leituras (telemetria simulada) ----------------
-- Sensor 1 - temperatura (limite 5 a 40 C): duas leituras fora da faixa
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (1,  1, TO_TIMESTAMP('2026-06-13 08:00', 'YYYY-MM-DD HH24:MI'), 22.50, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (2,  1, TO_TIMESTAMP('2026-06-13 10:00', 'YYYY-MM-DD HH24:MI'), 31.00, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (3,  1, TO_TIMESTAMP('2026-06-13 12:00', 'YYYY-MM-DD HH24:MI'), 38.90, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (4,  1, TO_TIMESTAMP('2026-06-13 14:00', 'YYYY-MM-DD HH24:MI'), 44.20, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (5,  1, TO_TIMESTAMP('2026-06-13 16:00', 'YYYY-MM-DD HH24:MI'), 52.30, 'N');
-- Sensor 2 - umidade (limite 30 a 65 %): duas leituras fora da faixa
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (6,  2, TO_TIMESTAMP('2026-06-12 09:00', 'YYYY-MM-DD HH24:MI'), 55.00, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (7,  2, TO_TIMESTAMP('2026-06-12 13:00', 'YYYY-MM-DD HH24:MI'), 61.00, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (8,  2, TO_TIMESTAMP('2026-06-12 17:00', 'YYYY-MM-DD HH24:MI'), 68.50, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (9,  2, TO_TIMESTAMP('2026-06-12 21:00', 'YYYY-MM-DD HH24:MI'), 74.00, 'N');
-- Sensor 3 - vibracao (limite 0 a 3 g): uma leitura fora da faixa
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (10, 3, TO_TIMESTAMP('2026-06-14 08:30', 'YYYY-MM-DD HH24:MI'), 0.80, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (11, 3, TO_TIMESTAMP('2026-06-14 09:30', 'YYYY-MM-DD HH24:MI'), 1.20, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (12, 3, TO_TIMESTAMP('2026-06-14 10:30', 'YYYY-MM-DD HH24:MI'), 2.90, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (13, 3, TO_TIMESTAMP('2026-06-14 11:30', 'YYYY-MM-DD HH24:MI'), 3.40, 'N');
-- Sensor 4 - umidade (limite 20 a 70 %): todas dentro da faixa
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (14, 4, TO_TIMESTAMP('2026-06-15 08:00', 'YYYY-MM-DD HH24:MI'), 40.00, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (15, 4, TO_TIMESTAMP('2026-06-15 12:00', 'YYYY-MM-DD HH24:MI'), 45.00, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (16, 4, TO_TIMESTAMP('2026-06-15 16:00', 'YYYY-MM-DD HH24:MI'), 50.00, 'N');
-- Sensor 5 - vibracao (limite 0 a 2.5 g): uma leitura fora da faixa
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (17, 5, TO_TIMESTAMP('2026-06-17 09:00', 'YYYY-MM-DD HH24:MI'), 1.00, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (18, 5, TO_TIMESTAMP('2026-06-17 11:00', 'YYYY-MM-DD HH24:MI'), 2.10, 'N');
INSERT INTO T_SH_LEITURA (ID_LEITURA, ID_SENSOR, DT_LEITURA, VL_LEITURA, FL_PROCESSADA) VALUES (19, 5, TO_TIMESTAMP('2026-06-17 13:00', 'YYYY-MM-DD HH24:MI'), 3.20, 'N');

COMMIT;

-- Conferencia rapida da carga
-- Esperado: USUARIO 6 | CURSO 4 | MATRICULA 9 | SERVICO 4 | FAVORITO 5 | PEDIDO 5 | SENSOR 5 | LEITURA 19
SELECT 'USUARIO'   AS TABELA, COUNT(*) AS QTD FROM T_SH_USUARIO   UNION ALL
SELECT 'CURSO',     COUNT(*) FROM T_SH_CURSO     UNION ALL
SELECT 'MATRICULA', COUNT(*) FROM T_SH_MATRICULA UNION ALL
SELECT 'SERVICO',   COUNT(*) FROM T_SH_SERVICO   UNION ALL
SELECT 'FAVORITO',  COUNT(*) FROM T_SH_FAVORITO  UNION ALL
SELECT 'PEDIDO',    COUNT(*) FROM T_SH_PEDIDO    UNION ALL
SELECT 'SENSOR',    COUNT(*) FROM T_SH_SENSOR    UNION ALL
SELECT 'LEITURA',   COUNT(*) FROM T_SH_LEITURA;
