-- =====================================================================
-- Smart HAS / Digital 360 - Fase 6
-- Script 99: Remove todos os objetos (para recriar do zero)
-- Erros "ORA-00942/ORA-04043/ORA-02289" (objeto inexistente) sao ignorados.
-- =====================================================================
BEGIN
    FOR o IN (
        SELECT 'DROP VIEW V_SH_PEDIDO_RISCO' AS cmd FROM DUAL UNION ALL
        SELECT 'DROP PROCEDURE SP_GERAR_RELATORIO_USUARIOS' FROM DUAL UNION ALL
        SELECT 'DROP PROCEDURE SP_RECALCULAR_RISCO' FROM DUAL UNION ALL
        SELECT 'DROP PROCEDURE SP_REGISTRAR_ALERTAS_SENSORES' FROM DUAL UNION ALL
        SELECT 'DROP FUNCTION FN_RESUMO_PEDIDO' FROM DUAL UNION ALL
        SELECT 'DROP FUNCTION FN_PROGRESSO_MEDIO_USUARIO' FROM DUAL UNION ALL
        SELECT 'DROP FUNCTION FN_CALCULA_RISCO' FROM DUAL UNION ALL
        SELECT 'DROP FUNCTION FN_NIVEL_RISCO' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_RELATORIO_USUARIO CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_RISCO_HIST CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_ALERTA CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_LEITURA CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_SENSOR CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_PEDIDO CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_FAVORITO CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_SERVICO CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_MATRICULA CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_CURSO CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP TABLE T_SH_USUARIO CASCADE CONSTRAINTS' FROM DUAL UNION ALL
        SELECT 'DROP SEQUENCE SEQ_SH_USUARIO' FROM DUAL UNION ALL
        SELECT 'DROP SEQUENCE SEQ_SH_PEDIDO' FROM DUAL UNION ALL
        SELECT 'DROP SEQUENCE SEQ_SH_LEITURA' FROM DUAL UNION ALL
        SELECT 'DROP SEQUENCE SEQ_SH_ALERTA' FROM DUAL UNION ALL
        SELECT 'DROP SEQUENCE SEQ_SH_RISCO' FROM DUAL UNION ALL
        SELECT 'DROP SEQUENCE SEQ_SH_RELATORIO' FROM DUAL
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE o.cmd;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE NOT IN (-942, -4043, -2289) THEN
                    RAISE;
                END IF;
        END;
    END LOOP;
END;
/
