erDiagram
    T_SH_USUARIO ||--o{ T_SH_MATRICULA : "matricula-se"
    T_SH_CURSO ||--o{ T_SH_MATRICULA : "possui"
    T_SH_USUARIO ||--o{ T_SH_FAVORITO : "favorita"
    T_SH_SERVICO ||--o{ T_SH_FAVORITO : "e favoritado"
    T_SH_USUARIO ||--o{ T_SH_PEDIDO : "realiza"
    T_SH_PEDIDO ||--o{ T_SH_SENSOR : "monitorado por"
    T_SH_SENSOR ||--o{ T_SH_LEITURA : "gera"
    T_SH_PEDIDO ||--o{ T_SH_ALERTA : "recebe"
    T_SH_LEITURA |o--o{ T_SH_ALERTA : "origina"
    T_SH_PEDIDO ||--o{ T_SH_RISCO_HIST : "historico"
    T_SH_USUARIO ||--o{ T_SH_RELATORIO_USUARIO : "resumo"

    T_SH_USUARIO {
        NUMBER ID_USUARIO PK
        VARCHAR2 NM_USUARIO
        VARCHAR2 NM_LOGIN UK
        CHAR NR_CPF UK
        DATE DT_NASCIMENTO
        VARCHAR2 DS_PERFIL
        VARCHAR2 NM_REGIAO
        DATE DT_CADASTRO
    }
    T_SH_CURSO {
        NUMBER ID_CURSO PK
        VARCHAR2 DS_TITULO
        VARCHAR2 DS_NIVEL
        NUMBER NR_CARGA_HORARIA
        NUMBER NR_TOTAL_MODULOS
    }
    T_SH_MATRICULA {
        NUMBER ID_MATRICULA PK
        NUMBER ID_USUARIO FK
        NUMBER ID_CURSO FK
        NUMBER NR_PROGRESSO
        DATE DT_INICIO
    }
    T_SH_SERVICO {
        NUMBER ID_SERVICO PK
        VARCHAR2 DS_TITULO
        VARCHAR2 DS_CATEGORIA
        VARCHAR2 NM_ORGAO
    }
    T_SH_FAVORITO {
        NUMBER ID_USUARIO PK,FK
        NUMBER ID_SERVICO PK,FK
        DATE DT_FAVORITO
    }
    T_SH_PEDIDO {
        NUMBER ID_PEDIDO PK
        VARCHAR2 CD_PEDIDO UK
        NUMBER ID_USUARIO FK
        VARCHAR2 DS_PRODUTO
        VARCHAR2 DS_REGIAO_ENTREGA
        NUMBER NR_DISTANCIA_KM
        DATE DT_PRAZO
        VARCHAR2 ST_PEDIDO
        VARCHAR2 NM_PARCEIRO
        CHAR FL_ESTOQUE
        NUMBER NR_HIST_ATRASOS
        NUMBER NR_REAGENDAMENTOS
    }
    T_SH_SENSOR {
        NUMBER ID_SENSOR PK
        NUMBER ID_PEDIDO FK
        VARCHAR2 DS_TIPO
        VARCHAR2 DS_UNIDADE
        NUMBER VL_LIMITE_MIN
        NUMBER VL_LIMITE_MAX
    }
    T_SH_LEITURA {
        NUMBER ID_LEITURA PK
        NUMBER ID_SENSOR FK
        TIMESTAMP DT_LEITURA
        NUMBER VL_LEITURA
        CHAR FL_PROCESSADA
    }
    T_SH_ALERTA {
        NUMBER ID_ALERTA PK
        NUMBER ID_PEDIDO FK
        NUMBER ID_LEITURA FK
        VARCHAR2 DS_ORIGEM
        VARCHAR2 DS_NIVEL
        VARCHAR2 DS_MENSAGEM
        TIMESTAMP DT_ALERTA
        VARCHAR2 ST_ALERTA
    }
    T_SH_RISCO_HIST {
        NUMBER ID_RISCO PK
        NUMBER ID_PEDIDO FK
        NUMBER NR_SCORE
        VARCHAR2 DS_NIVEL
        VARCHAR2 DS_RECOMENDACAO
        TIMESTAMP DT_CALCULO
    }
    T_SH_RELATORIO_USUARIO {
        NUMBER ID_RELATORIO PK
        NUMBER ID_USUARIO FK
        TIMESTAMP DT_GERACAO
        NUMBER QT_CURSOS
        NUMBER VL_PROGRESSO_MEDIO
        NUMBER QT_PEDIDOS
        NUMBER QT_ALERTAS_ABERTOS
        VARCHAR2 DS_CLASSIFICACAO
    }
